### ISSUE TITLE
How can I use/start it? Could you publish instruction, like a quick start?

### ISSUE THREAD

**Issue by Geckostya** [hiperbou/kotlin-unreal#1]
I've dowloaded the project and don't understand how UE4 is connected with Kotlin code. It would be good idea to publish some instruction to setup your project in README.md or Wiki
Thanks

**Comment by hiperbou** [comment]
I have added some new features and updated the readme and wrote some instructions on the newly created wiki:

https://github.com/hiperbou/kotlin-unreal/wiki
