### ISSUE TITLE
Requesting for milestone and ways of communication about the project like discord

### ISSUE THREAD

**Issue by ronjunevaldoz** [hiperbou/kotlin-unreal#15]
### Requesting for milestone and ways of communication about the project like discord
Can you include the possible feature in the future? I am interested in this project because and a Kotlin fan and looking for a better game engine using it. Also if possible can you explain how Kotlin works on the Unreal Engine technically?

**Comment by aqua-pro** [comment]
> ### Requesting for milestone and ways of communication about the project like discord
> 
> Can you include the possible feature in the future? I am interested in this project because and a Kotlin fan and looking for a better game engine using it. Also if possible can you explain how Kotlin works on the Unreal Engine technically?

I feel exactly the same way!

**Comment by hiperbou** [comment]
I have enabled the new Github's Discussions on this project as I think a public forum would fit better than a Discord server.

https://github.com/hiperbou/kotlin-unreal/discussions
