### ISSUE TITLE
I Cant't use any package except out-of-box packages

### ISSUE THREAD

**Issue by burakakca** [hiperbou/kotlin-unreal#25]
For example , I try to add ktor server packages from below with maven;
![image](https://user-images.githubusercontent.com/56919004/201952236-4a5e586d-ef6b-4196-bd4d-4eec5993d7a3.png)

kotlin-examples.iml file updated and Extarnel libraries show me the added ktor package but when I do import that package can't access it

Also , Can we use gradle or maven ? .

**Comment by hiperbou** [comment]
I added the coroutines library to the project as an example as how to add external dependencies.
I tried it again just to test it and it seems to work for me.

Goin to Project Structure / Project Settings / Libraries and click on the + button and select "from Maven".
On the search box put the package you can find on the maven repository, and click on de dropdown to see all the matching options. And I think that here is the trick: Search for the **Javascript** version of the library. Usually the one including a "-js" suffix.

Try it with **com.soywiz.korlibs.kds** wich is a really nice library with some cool to have data structures for Kotlin.

![libs1](https://user-images.githubusercontent.com/12442874/202895740-3f09d807-e025-404b-b23e-8537de4201cd.jpg)

It will be added, and as you say it will modifiy the .iml and add a new file on kotlin-examples\.idea\libraries
![libs2](https://user-images.githubusercontent.com/12442874/202895800-6e1c221d-c386-4d0c-8b86-c4da4343109c.jpg)

You should be able to use the library from the code right away, 

One last step will be needed to make it work on runtime. Build on IntelliJ, and copy the new *.js files you will find on kotlin-unreal\kotlin-examples\out\production\kotlin-examples\lib to kotlin-unreal/Content/Scripts

In my case I copied kds-root-kds-jsLegacy.js

This should work on Unreal, without problems



On the other side, if you're trying to use Ktor, you'll probably get nowhere, as I don't think Ktor supports a V8 backend inside Unreal. Ktor would be a better fit for a browser client or a nodejs project. Although all of them are Javascript, the environments where they run are different and each one has its own low level implementation, and Ktom may or may not work out of the box.

Unreal.js (and so kotlin-unreal) definitely has network capabilities, as can be seen in some [examples](https://github.com/ncsoft/Unreal.js-demo/blob/51cffb0a54d677bd261dc88f1cab9e1f4ffa399c/Content/Scripts/demos/demo-rest.js) and [here](https://github.com/ncsoft/Unreal.js/blob/33329c82871e830586e82bed09dc278135e8c80a/Examples/Content/Scripts/helloJS.js)

**Comment by burakakca** [comment]
I understand what you say, ktor may not work in UE4 but my problem is a little bit different.

I can't import package
![image](https://user-images.githubusercontent.com/56919004/202900102-713e1bb3-e7bb-4562-997f-7e71ae0701c7.png)

**Comment by hiperbou** [comment]
Check if you have the library added to de kotlin-example module. When
adding a library intelliJ asks if you want to add it to all the modules
automatically (or something like that).

[image: dependencies.jpg]

**Comment by burakakca** [comment]
Okay, thanks. I get it now. I need the be sure of js implementation package must downloaded
