### ISSUE TITLE
Dynamic scripting?

### ISSUE THREAD

**Issue by mvsoom** [hiperbou/kotlin-unreal#29]
Hi, could this be used to script the game during runtime? Meaning that the player could influence the game by executing Kotlin scipts during gameplay, for example using the console.

**Comment by hiperbou** [comment]
That could be doable, check the Hot Reload feature in the wiki

https://github.com/hiperbou/kotlin-unreal/wiki/Hot-Reload

**Comment by mvsoom** [comment]
OK, I will check it out. Thanks!
